version: '3.9'

services:
  backend:
    build: ./library_back
    container_name: "django"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    container_name: "${POSTGRES_DB}"
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    env_file:
      - .env
  frontend:
    container_name: react-frontend
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./library_front:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
  nginx:
    image: nginx:1.18-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  postgres_db:
  nginx_vol: