version: '3.9'

services:
  api:
    build: ./library_back
    container_name: "django"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.5-alpine
    container_name: "${POSTGRES_DB}"
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  app:
    container_name: react-app
    build:
      context: ./library_front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./library_front:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data:
