name: Application CD

on:
  workflow_run:
    workflows: [ Application CI ]
    types:
      - completed
    branches: [ main ]

jobs:
  run_app :
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend
        id: build_back
        uses: docker/build-push-action@v2
        with:
          context: ./library_back
          file: ./library_back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gces-application:latest

      - name: Build and push frontend
        id: build_front
        uses: docker/build-push-action@v2
        with:
          context: ./library_front
          file: ./library_front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gces-application:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}