name: Application CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build e Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d

  frontend-lint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Frontend ESlint
        working-directory: ./library_front
        run: eslint . --ext .js,.jsx,.ts,.tsx
