name: Application CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build e Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d

  frontend-lint:
    name: Frontend lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Frontend ESlint
        run: docker exec react_frontend npx eslint --fix src/

  backend-lint:
    name: Backend lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Backend ESlint
        run: docker exec  django flake8 --exit-zero --ignore=E501 src/ 

  test-frontend:
    name: Testes frontend reactjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Teste fronted
        run: docker exec react_frontend sh -c "CI=true npm test --watchAll=false"
  
  test-backend:
    name: Testes backend django
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Teste backend
        run: docker exec django sh -c "python /library_back/manage.py test"