name: Application CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build e Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d

  frontend-lint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Frontend ESlint
        run: docker exec react_frontend npx eslint --fix src/

  backend-lint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d
      - name: Backend ESlint
        run: docker exec django pylint -j ./src/ ./book ./accounts